import { StyleSheet } from 'react-native';



export const styles = StyleSheet.create({
  container: { paddingBottom: 40, backgroundColor: '#f6f8fb' },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  header: { backgroundColor: '#fff', padding: 24, alignItems: 'center', paddingTop: 60, borderBottomWidth: 1, borderBottomColor: '#f1f5f9' },
  avatarWrap: { position: 'relative' },
  avatar: { width: 110, height: 110, borderRadius: 55, backgroundColor: '#e6eefc' },
  avatarPlaceholder: { width: 110, height: 110, borderRadius: 55, backgroundColor: '#0b5fff', justifyContent: 'center', alignItems: 'center' },
  avatarLetter: { color: '#fff', fontSize: 44, fontWeight: 'bold' },
  editBadge: { position: 'absolute', bottom: 2, right: 2, backgroundColor: '#0b5fff', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12, borderWidth: 3, borderColor: '#fff' },
  editBadgeText: { fontSize: 11, color: '#fff', fontWeight: 'bold' },
  headerInfo: { alignItems: 'center', marginTop: 16 },
  name: { fontSize: 24, fontWeight: '800', color: '#111827' },
  badgeRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 6 },
  role: { color: '#0b5fff', fontWeight: '700', fontSize: 14, backgroundColor: '#eff6ff', paddingHorizontal: 10, paddingVertical: 2, borderRadius: 6 },
  locationBadge: { color: '#6b7280', fontSize: 14, fontWeight: '500' },
  email: { color: '#9ca3af', marginTop: 4, fontSize: 14 },
  closeView: { marginTop: 15 },
  card: { padding: 20 },
  sectionTitle: { fontSize: 13, fontWeight: '800', color: '#9ca3af', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 8, marginTop: 18 },
  sectionText: { fontSize: 16, color: '#374151', backgroundColor: '#fff', padding: 14, borderRadius: 12, borderWidth: 1, borderColor: '#f1f5f9', lineHeight: 22 },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 10 },
  profileTag: { backgroundColor: '#0b5fff', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20 },
  profileTagText: { color: '#fff', fontSize: 12, fontWeight: '700' },
  statsRow: { flexDirection: 'row', gap: 12, marginTop: 15 },
  statItem: { flex: 1, backgroundColor: '#fff', padding: 15, borderRadius: 15, alignItems: 'center', borderWidth: 1, borderColor: '#f1f5f9' },
  statLabel: { fontSize: 12, color: '#9ca3af', marginBottom: 4 },
  statValue: { fontSize: 18, fontWeight: '800', color: '#111827' },
  input: { backgroundColor: '#f9fafb', padding: 14, borderRadius: 12, borderWidth: 1, borderColor: '#e5e7eb', fontSize: 16, marginTop: 8 },
  textArea: { backgroundColor: '#f9fafb', padding: 14, borderRadius: 12, borderWidth: 1, borderColor: '#e5e7eb', fontSize: 16, height: 100, textAlignVertical: 'top' },
  primaryBtn: { backgroundColor: '#0b5fff', padding: 16, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  primaryText: { color: '#fff', fontWeight: '800', fontSize: 15 },
  secondaryBtn: { backgroundColor: '#f3f4f6', padding: 16, borderRadius: 14, alignItems: 'center' },
  secondaryText: { color: '#4b5563', fontWeight: '800' },
  logoutBtn: { padding: 15, alignItems: 'center' },
  logoutText: { color: '#ef4444', fontWeight: '800', fontSize: 15 },
  modalBackground: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'center', padding: 24 },
  modalBox: { backgroundColor: '#fff', borderRadius: 24, padding: 24, shadowColor: '#000', shadowOpacity: 0.1, shadowRadius: 20, elevation: 10 },
  modalTitle: { fontSize: 20, fontWeight: '800', marginBottom: 20, textAlign: 'center', color: '#111827' },
});